"""Shared output utilities used by pdf_builder, docx_builder, and FileOutputHandler."""

import logging
import re
from pathlib import Path
from typing import List, Optional

# Regex that matches page-header lines generated by generate_text(), e.g.
# "-- Page 4 --" (trailing whitespace stripped by _normalize_paragraphs).
_PAGE_MARKER_RE = re.compile(r'^--\s*Page\s+(\d+)\s*--\s*$')


def _emit_message(
    message: str,
    level: int = logging.INFO,
    log_message: Optional[str] = None,
    leading_newline: bool = False,
) -> None:
    """Emit a synchronized log + console message."""
    logging.log(level, log_message or message)
    prefix = "\n" if leading_newline else ""
    print(f"{prefix}{message}")


def _normalize_paragraphs(content: str) -> list[str]:
    """Split content into normalized paragraphs for document output."""
    paragraphs: list[str] = []
    for paragraph in content.split('\n\n'):
        stripped = paragraph.strip()
        if stripped:
            paragraphs.append(stripped.replace('\n', ' '))
    return paragraphs


def _parse_md_table_block(block: str) -> Optional[List[List[str]]]:
    """Return a grid of cell strings if *block* is a Markdown table; otherwise None."""
    # Normalise <br> variants that models sometimes emit instead of real newlines.
    block = re.sub(r'<br\s*/?>', '\n', block, flags=re.IGNORECASE)
    lines = [line.strip() for line in block.strip().splitlines() if line.strip()]
    if len(lines) < 2:
        return None
    pipe_re = re.compile(r'^\|.*\|$')
    sep_re = re.compile(r'^\|[\s\-\|:]+\|$')
    if not all(pipe_re.match(line) for line in lines):
        return None
    if not any(sep_re.match(line) for line in lines):
        return None
    rows: List[List[str]] = []
    for line in lines:
        if sep_re.match(line):
            continue
        cells = [cell.strip() for cell in line[1:-1].split('|')]
        rows.append(cells)
    return rows if rows else None


def _extract_markdown_tables(content: str) -> tuple[str, dict[str, List[List[str]]]]:
    """Replace Markdown table blocks with ``[MD_TABLE_N]`` placeholder tokens.

    Returns the modified content and a registry mapping each token to its
    row/cell grid, ready to be merged into an existing table_registry.
    """
    registry: dict[str, List[List[str]]] = {}
    counter = 0
    new_blocks: list[str] = []
    for block in content.split('\n\n'):
        rows = _parse_md_table_block(block)
        if rows is not None:
            counter += 1
            key = f"[MD_TABLE_{counter}]"
            registry[key] = rows
            new_blocks.append(key)
        else:
            new_blocks.append(block)
    return '\n\n'.join(new_blocks), registry


def _render_table_as_ascii(rows: List[List[str]]) -> str:
    """Render a row/cell grid as an ASCII box table."""
    if not rows:
        return ''
    n_cols = max(len(row) for row in rows)
    padded = [row + [''] * (n_cols - len(row)) for row in rows]
    col_widths = [
        max(max(len(padded[r][c]) for r in range(len(padded))), 3)
        for c in range(n_cols)
    ]
    sep = '+' + '+'.join('-' * (w + 2) for w in col_widths) + '+'
    lines = [sep]
    for i, row in enumerate(padded):
        cells = ' | '.join(cell.ljust(col_widths[j]) for j, cell in enumerate(row))
        lines.append(f'| {cells} |')
        if i == 0:
            lines.append(sep)
    lines.append(sep)
    return '\n'.join(lines)


def _render_markdown_tables_as_ascii(content: str) -> str:
    """Replace Markdown table blocks with ASCII art tables (for plain-text output)."""
    new_blocks: list[str] = []
    for block in content.split('\n\n'):
        rows = _parse_md_table_block(block)
        if rows is not None:
            new_blocks.append(_render_table_as_ascii(rows))
        else:
            new_blocks.append(block)
    return '\n\n'.join(new_blocks)


def save_to_text_file(content: str, output_path: str, label: str) -> None:
    """Save content to a text file."""
    try:
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(content)
        _emit_message(
            f"{label} saved to: {Path(output_path).name}",
            level=logging.INFO,
            log_message=f'{label} saved to text file: {output_path}',
            leading_newline=True,
        )
    except (OSError, UnicodeError) as e:
        _emit_message(
            f"Error saving to text file: {e}",
            level=logging.ERROR,
        )


def append_to_text_file(content: str, output_path: str, label: str) -> None:
    """Append content to a text file."""
    try:
        with open(output_path, 'a', encoding='utf-8') as f:
            f.write(content + '\n\n')
        _emit_message(
            f"Page appended to: {Path(output_path).name}",
            level=logging.INFO,
            log_message=f'{label} appended to text file: {output_path}',
        )
    except (OSError, UnicodeError) as e:
        _emit_message(
            f"Error appending to text file: {e}",
            level=logging.ERROR,
        )
