"""File output handler: writes translations to .txt, .pdf, or .docx with CJK font support."""

import logging
import re
from io import BytesIO
from pathlib import Path
from typing import List, Optional
from datetime import datetime

from .font_resolver import get_docx_font, get_pdf_font
from ..settings import DEFAULT_FONT_SIZE

# PDF page margins (in points, 72 pts = 1 inch)
PDF_MARGINS = {
    'left': 72,
    'right': 72,
    'top': 72,
    'bottom': 18,
}

# Maximum width (EMU) an inserted image may occupy inside a Word document.
# Derived from US Letter (8.5") with 1" margins on each side: 6.5" × 914400 EMU/inch.
_MAX_IMAGE_WIDTH_EMU: int = 5_943_600

# Regex that matches the page-header lines generated by generate_text(), e.g.
# "-- Page 4 --" or "-- Page 4 -- " (trailing whitespace stripped by
# _normalize_paragraphs before this is applied).
_PAGE_MARKER_RE = re.compile(r'^--\s*Page\s+(\d+)\s*--\s*$')



def generate_output_filename(input_file: str, source_lang: str, target_lang: str, extension: str = '.txt') -> str:
    """Generate an output filename based on input file and languages."""
    input_path = Path(input_file)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    output_name = f"{input_path.stem}_{source_lang}to{target_lang}_{timestamp}{extension}"
    return str(input_path.parent / output_name)


class FileOutputHandler:
    """Handles saving translations to various file formats."""

    @staticmethod
    def _emit_message(
        message: str,
        level: int = logging.INFO,
        log_message: Optional[str] = None,
        leading_newline: bool = False,
    ) -> None:
        """Emit a synchronized log + console message."""
        logging.log(level, log_message or message)
        prefix = "\n" if leading_newline else ""
        print(f"{prefix}{message}")

    @staticmethod
    def _normalize_paragraphs(content: str) -> list[str]:
        """Split content into normalized paragraphs for document output."""
        paragraphs: list[str] = []
        for paragraph in content.split('\n\n'):
            stripped = paragraph.strip()
            if stripped:
                paragraphs.append(stripped.replace('\n', ' '))
        return paragraphs

    @staticmethod
    def _parse_md_table_block(block: str) -> Optional[List[List[str]]]:
        """Return a grid of cell strings if *block* is a Markdown table; otherwise None."""
        # Normalise <br> variants that models sometimes emit instead of real newlines.
        block = re.sub(r'<br\s*/?>', '\n', block, flags=re.IGNORECASE)
        lines = [line.strip() for line in block.strip().splitlines() if line.strip()]
        if len(lines) < 2:
            return None
        pipe_re = re.compile(r'^\|.*\|$')
        sep_re = re.compile(r'^\|[\s\-\|:]+\|$')
        if not all(pipe_re.match(line) for line in lines):
            return None
        if not any(sep_re.match(line) for line in lines):
            return None
        rows: List[List[str]] = []
        for line in lines:
            if sep_re.match(line):
                continue
            cells = [cell.strip() for cell in line[1:-1].split('|')]
            rows.append(cells)
        return rows if rows else None

    @staticmethod
    def _extract_markdown_tables(content: str) -> tuple[str, dict[str, List[List[str]]]]:
        """Replace Markdown table blocks with ``[MD_TABLE_N]`` placeholder tokens.

        Returns the modified content and a registry mapping each token to its
        row/cell grid, ready to be merged into an existing table_registry.
        """
        registry: dict[str, List[List[str]]] = {}
        counter = 0
        new_blocks: list[str] = []
        for block in content.split('\n\n'):
            rows = FileOutputHandler._parse_md_table_block(block)
            if rows is not None:
                counter += 1
                key = f"[MD_TABLE_{counter}]"
                registry[key] = rows
                new_blocks.append(key)
            else:
                new_blocks.append(block)
        return '\n\n'.join(new_blocks), registry

    @staticmethod
    def _render_table_as_ascii(rows: List[List[str]]) -> str:
        """Render a row/cell grid as an ASCII box table."""
        if not rows:
            return ''
        n_cols = max(len(row) for row in rows)
        padded = [row + [''] * (n_cols - len(row)) for row in rows]
        col_widths = [
            max(max(len(padded[r][c]) for r in range(len(padded))), 3)
            for c in range(n_cols)
        ]
        sep = '+' + '+'.join('-' * (w + 2) for w in col_widths) + '+'
        lines = [sep]
        for i, row in enumerate(padded):
            cells = ' | '.join(cell.ljust(col_widths[j]) for j, cell in enumerate(row))
            lines.append(f'| {cells} |')
            if i == 0:
                lines.append(sep)
        lines.append(sep)
        return '\n'.join(lines)

    @staticmethod
    def _render_markdown_tables_as_ascii(content: str) -> str:
        """Replace Markdown table blocks with ASCII art tables (for plain-text output)."""
        new_blocks: list[str] = []
        for block in content.split('\n\n'):
            rows = FileOutputHandler._parse_md_table_block(block)
            if rows is not None:
                new_blocks.append(FileOutputHandler._render_table_as_ascii(rows))
            else:
                new_blocks.append(block)
        return '\n\n'.join(new_blocks)

    @staticmethod
    def _apply_docx_table_borders(table) -> None:  # type: ignore[no-untyped-def]
        """Apply thin (0.5 pt) black borders to all sides of a python-docx Table."""
        try:
            from docx.oxml.ns import qn
            from docx.oxml import OxmlElement
            tbl_pr = table._tbl.tblPr
            tbl_borders = OxmlElement('w:tblBorders')
            for side in ('top', 'left', 'bottom', 'right', 'insideH', 'insideV'):
                el = OxmlElement(f'w:{side}')
                el.set(qn('w:val'), 'single')
                el.set(qn('w:sz'), '4')   # 4 × 1/8 pt = 0.5 pt
                el.set(qn('w:space'), '0')
                el.set(qn('w:color'), '000000')
                tbl_borders.append(el)
            tbl_pr.append(tbl_borders)
        except Exception as _be:
            logging.warning(f"Could not apply table borders: {_be}")

    @staticmethod
    def _resolve_output_path(
        input_file: Optional[str],
        output_file: Optional[str],
        auto_save: bool,
        source_lang: str,
        target_lang: str,
        default_extension: str = '.txt',
    ) -> Optional[str]:
        """Resolve the output path from explicit or auto-save settings."""
        if output_file:
            return output_file
        if auto_save and input_file:
            return generate_output_filename(input_file, source_lang, target_lang, default_extension)
        return None

    @staticmethod
    def _ensure_parent_directory(output_path: str) -> None:
        """Ensure the parent directory for output exists."""
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)

    @staticmethod
    def _fallback_to_text(content: str, output_path: str, label: str) -> None:
        """Fallback to text output when rich document generation fails."""
        text_output_path = str(Path(output_path).with_suffix('.txt'))
        FileOutputHandler.save_to_text_file(content, text_output_path, label)
    
    @staticmethod
    def save_to_text_file(content: str, output_path: str, label: str) -> None:
        """Save content to a text file."""
        try:
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write(content)
            FileOutputHandler._emit_message(
                f"{label} saved to: {Path(output_path).name}",
                level=logging.INFO,
                log_message=f'{label} saved to text file: {output_path}',
                leading_newline=True,
            )
        except (OSError, UnicodeError) as e:
            FileOutputHandler._emit_message(
                f"Error saving to text file: {e}",
                level=logging.ERROR,
            )

    @staticmethod
    def append_to_text_file(content: str, output_path: str, label: str) -> None:
        """Append content to a text file."""
        try:
            with open(output_path, 'a', encoding='utf-8') as f:
                f.write(content + '\n\n')
            FileOutputHandler._emit_message(
                f"Page appended to: {Path(output_path).name}",
                level=logging.INFO,
                log_message=f'{label} appended to text file: {output_path}',
            )
        except (OSError, UnicodeError) as e:
            FileOutputHandler._emit_message(
                f"Error appending to text file: {e}",
                level=logging.ERROR,
            )
    
    @staticmethod
    def save_to_pdf(content: str, output_path: str, custom_font: Optional[str] = None,
                    target_lang: Optional[str] = None,
                    table_registry: Optional[dict] = None,
                    font_size: Optional[int] = None,
                    *,
                    label: str) -> None:
        """Save content to a PDF file using reportlab.

        If *table_registry* is provided, ``[TABLE_N]`` placeholder paragraphs
        are rendered as reportlab ``Table`` flowables instead of plain text.
        """
        try:
            from reportlab.lib.pagesizes import letter
            from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
            from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Flowable, Table, TableStyle
            from reportlab.lib import colors
            
            # Create PDF document
            doc = SimpleDocTemplate(
                output_path, 
                pagesize=letter,
                rightMargin=PDF_MARGINS['right'],
                leftMargin=PDF_MARGINS['left'],
                topMargin=PDF_MARGINS['top'],
                bottomMargin=PDF_MARGINS['bottom']
            )
            
            fs = font_size if font_size is not None else DEFAULT_FONT_SIZE

            # Create story (content container)
            story: list[Flowable] = []
            styles = getSampleStyleSheet()
            
            # Configure font - use Times-Roman for English unless custom font specified
            if not custom_font and target_lang == 'English':
                font_name = 'Times-Roman'
                logging.debug(f"Using Times-Roman for English translation (target_lang={target_lang})")
            else:
                font_name = get_pdf_font(custom_font)
                logging.debug(f"Using CJK font: {font_name} (custom_font={custom_font}, target_lang={target_lang})")
            
            # Create paragraph style with proper font
            try:
                normal_style = ParagraphStyle(
                    'CJKNormal',
                    parent=styles['Normal'],
                    fontName=font_name,
                    fontSize=fs,
                    leading=round(fs * 1.5),
                    spaceAfter=fs,
                    encoding='utf-8'
                )
                logging.debug(f"Created paragraph style with font: {font_name}")
            except (TypeError, ValueError, KeyError) as e:
                logging.warning(f"Failed to create custom style with font {font_name}: {e}")
                normal_style = styles['Normal']
                font_name = 'Times-Roman'  # Fallback to default
            
            fallback_style = ParagraphStyle(
                'FallbackCJK',
                parent=styles['Normal'],
                fontName='Times-Roman',
                fontSize=fs,
                leading=round(fs * 1.5),
                spaceAfter=fs
            )

            # Extract any inline Markdown tables the model returned and merge
            # them into the table_registry so the existing rendering path handles them.
            content, _md_reg = FileOutputHandler._extract_markdown_tables(content)
            if _md_reg:
                table_registry = dict(table_registry) if table_registry else {}
                table_registry.update(_md_reg)

            # Split content into paragraphs and add to story
            for i, clean_text in enumerate(FileOutputHandler._normalize_paragraphs(content), start=1):

                # --- Table placeholder: render as a reportlab Table flowable ---
                if table_registry and clean_text.strip() in table_registry:
                    rows = table_registry[clean_text.strip()]
                    if rows:
                        try:
                            # Build cell data — each cell wrapped in a Paragraph for wrapping
                            cell_data = [
                                [Paragraph(cell or '', normal_style) for cell in row]
                                for row in rows
                            ]
                            tbl = Table(cell_data, hAlign='LEFT')
                            tbl.setStyle(TableStyle([
                                ('GRID',       (0, 0), (-1, -1), 0.5, colors.black),
                                ('BACKGROUND', (0, 0), (-1, 0),  colors.lightgrey),
                                ('FONTNAME',   (0, 0), (-1, -1), font_name),
                                ('FONTSIZE',   (0, 0), (-1, -1), max(fs - 2, 6)),
                                ('TOPPADDING',    (0, 0), (-1, -1), 4),
                                ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
                            ]))
                            story.append(tbl)
                            story.append(Spacer(1, 12))
                            logging.debug(
                                f"Inserted PDF table for '{clean_text.strip()}' "
                                f"({len(rows)} row(s))"
                            )
                            continue
                        except Exception as tbl_err:
                            logging.warning(
                                f"Could not render PDF table for '{clean_text.strip()}': {tbl_err}; "
                                "falling back to plain text"
                            )
                            # fall through to plain-paragraph rendering below

                try:
                    paragraph = Paragraph(clean_text, normal_style)
                    story.append(paragraph)
                    story.append(Spacer(1, 12))
                    logging.debug(f"Successfully added paragraph {i} with font {font_name}")
                except Exception as paragraph_error:
                    logging.warning(f"Error processing paragraph {i} with font {font_name}: {paragraph_error}")
                    try:
                        paragraph = Paragraph(clean_text, fallback_style)
                        story.append(paragraph)
                        story.append(Spacer(1, 12))
                        logging.debug(f"Used fallback font Times-Roman for paragraph {i}")
                    except Exception as fallback_error:
                        logging.warning(f"Fallback font also failed for paragraph {i}: {fallback_error}")
                        ascii_safe_text = clean_text.encode('ascii', 'ignore').decode('ascii')
                        if ascii_safe_text.strip():
                            paragraph = Paragraph(ascii_safe_text, styles['Normal'])
                            story.append(paragraph)
                            story.append(Spacer(1, 12))
                            logging.warning(f"Used ASCII-safe fallback for paragraph {i}")
                        else:
                            logging.warning(f"Paragraph {i} contained no ASCII-safe characters, skipping")
            
            # Build PDF
            if story:
                doc.build(story)
                FileOutputHandler._emit_message(
                    f"{label} saved to PDF: {Path(output_path).name}",
                    level=logging.INFO,
                    log_message=f'{label} saved to PDF file: {output_path}',
                    leading_newline=True,
                )
                if font_name != 'Times-Roman':
                    FileOutputHandler._emit_message(f"Used font: {font_name}", level=logging.DEBUG)
            else:
                FileOutputHandler._emit_message(
                    "Error: No content could be processed for PDF generation",
                    level=logging.ERROR,
                    log_message="No content could be processed for PDF generation",
                )
                FileOutputHandler._fallback_to_text(content, output_path, label)
            
        except ImportError:
            FileOutputHandler._emit_message(
                "Warning: reportlab not installed. Saving as text file instead.",
                level=logging.WARNING,
                log_message='reportlab not installed. Falling back to text file.',
            )
            FileOutputHandler._fallback_to_text(content, output_path, label)
        except Exception as e:
            FileOutputHandler._emit_message(
                f"Error generating PDF: {e}",
                level=logging.ERROR,
                log_message=f'Error saving to PDF: {e}',
            )
            FileOutputHandler._emit_message(
                "Falling back to text file for reliable CJK character support...",
                level=logging.WARNING,
            )
            FileOutputHandler._fallback_to_text(content, output_path, label)
    
    @staticmethod
    def save_to_docx(content: str, output_path: str, custom_font: Optional[str] = None,
                     target_lang: Optional[str] = None, media: Optional[List] = None,
                     table_registry: Optional[dict] = None,
                     font_size: Optional[int] = None,
                     *,
                     label: str) -> None:
        """Save content to a Word document using python-docx.

        If *media* is provided (a list of :class:`~src.models.embedded_media.EmbeddedMedia`
        items), each image is reinserted at the proportionally equivalent position in
        the translated document.

        If *table_registry* is provided (a mapping from ``"[TABLE_N]"`` placeholder
        tokens to translated cell grids), any paragraph whose text is exactly a
        ``[TABLE_N]`` token is replaced by a proper Word ``Table`` object instead
        of being written as a paragraph.
        """
        try:
            from docx import Document
            from docx.shared import Inches, Pt, Emu

            # Create a new document
            doc = Document()
            fs = font_size if font_size is not None else DEFAULT_FONT_SIZE

            # Set up margins (similar to PDF margins)
            sections = doc.sections
            for section in sections:
                section.top_margin = Inches(1.0)
                section.bottom_margin = Inches(1.0)
                section.left_margin = Inches(1.0)
                section.right_margin = Inches(1.0)

            # Get font name for CJK support
            if not custom_font and target_lang == 'English':
                font_name = 'Times New Roman'
                logging.debug(f"Using Times New Roman for English translation (target_lang={target_lang})")
            else:
                font_name = get_docx_font(custom_font)
                logging.debug(f"Using CJK font for Word: {font_name} (custom_font={custom_font}, target_lang={target_lang})")

            # --- Media routing -------------------------------------------------
            # Images from PDF sources carry page_number (0-based PDF page index)
            # and are anchored to the corresponding "-- Page N --" markers in the
            # translated output.  Images from DOCX sources have page_number=None
            # and fall back to fractional (cursor-based) placement.
            sorted_media = sorted(media, key=lambda m: m.position_fraction) if media else []

            pdf_media_by_page: dict[int, list] = {}
            frac_sorted: list = []
            for _m in sorted_media:
                if _m.page_number is not None:
                    pdf_media_by_page.setdefault(_m.page_number, []).append(_m)
                else:
                    frac_sorted.append(_m)

            frac_cursor = 0
            pending_pdf_images: list = []

            def _do_insert_image(item) -> None:  # type: ignore[no-untyped-def]
                """Write a single EmbeddedMedia item into the document."""
                try:
                    img_para = doc.add_paragraph()
                    img_run = img_para.add_run()
                    # Cap width to the text-area; height scales automatically.
                    display_width = Emu(
                        min(item.width_emu, _MAX_IMAGE_WIDTH_EMU)
                        if item.width_emu
                        else _MAX_IMAGE_WIDTH_EMU
                    )
                    img_data = BytesIO(item.data)
                    try:
                        img_run.add_picture(img_data, width=display_width)
                    except Exception:
                        # python-docx cannot handle some formats (e.g. TIFF,
                        # CMYK JPEG).  Try converting to PNG via Pillow.
                        try:
                            from PIL import Image as _PILImage
                            img_data.seek(0)
                            pil_img = _PILImage.open(img_data)
                            # Convert CMYK or P-mode to RGB before saving as PNG
                            if pil_img.mode not in ('RGB', 'RGBA', 'L'):
                                pil_img = pil_img.convert('RGB')
                            png_buf = BytesIO()
                            pil_img.save(png_buf, format='PNG')
                            png_buf.seek(0)
                            img_run.add_picture(png_buf, width=display_width)
                            logging.debug(
                                f"Converted image at fraction "
                                f"{item.position_fraction:.3f} to PNG for insertion."
                            )
                        except Exception as conv_err:
                            logging.warning(
                                f"Could not insert image at fraction "
                                f"{item.position_fraction:.3f}: "
                                f"{type(conv_err).__name__}: {conv_err}"
                            )
                    logging.debug(f"Inserted image at position_fraction={item.position_fraction:.3f}")
                except Exception as img_err:
                    logging.warning(
                        f"Could not insert image at fraction {item.position_fraction:.3f}: "
                        f"{type(img_err).__name__}: {img_err}"
                    )

            def _flush_pending_pdf_images() -> None:
                """Insert all buffered PDF-page images into the document."""
                nonlocal pending_pdf_images
                for _item in pending_pdf_images:
                    _do_insert_image(_item)
                pending_pdf_images = []

            def _insert_frac_images_up_to(para_fraction: float) -> None:
                """Insert fraction-based (DOCX-source) images up to para_fraction."""
                nonlocal frac_cursor
                while frac_cursor < len(frac_sorted) and frac_sorted[frac_cursor].position_fraction <= para_fraction:
                    _do_insert_image(frac_sorted[frac_cursor])
                    frac_cursor += 1

            # Extract any inline Markdown tables and merge into table_registry.
            content, _md_reg = FileOutputHandler._extract_markdown_tables(content)
            if _md_reg:
                table_registry = dict(table_registry) if table_registry else {}
                table_registry.update(_md_reg)

            translated_paras = FileOutputHandler._normalize_paragraphs(content)
            total_paras = len(translated_paras) or 1

            # Split content into paragraphs and add to document
            for i, clean_text in enumerate(translated_paras, start=1):
                para_fraction = i / total_paras

                # --- Page-marker detection for PDF-source images ---------------
                # When we see "-- Page N --" we flush the previous page's images
                # (inserting them at the end of that page's content block) then
                # queue the new page's images for later insertion.
                if pdf_media_by_page:
                    _pm = _PAGE_MARKER_RE.match(clean_text)
                    if _pm:
                        _flush_pending_pdf_images()
                        _page_label = int(_pm.group(1))  # 1-based label
                        pending_pdf_images = list(pdf_media_by_page.get(_page_label - 1, []))

                # --- Table placeholder: replace with a Word Table object ---
                if table_registry and clean_text.strip() in table_registry:
                    rows = table_registry[clean_text.strip()]
                    if rows:
                        try:
                            n_cols = max(len(row) for row in rows)
                            tbl = doc.add_table(rows=len(rows), cols=n_cols)
                            FileOutputHandler._apply_docx_table_borders(tbl)
                            for r_idx, row in enumerate(rows):
                                for c_idx, cell_text in enumerate(row):
                                    if c_idx < n_cols:
                                        cell = tbl.cell(r_idx, c_idx)
                                        cell.text = cell_text
                                        for para in cell.paragraphs:
                                            for run in para.runs:
                                                run.font.name = font_name
                                                run.font.size = Pt(fs)
                            logging.debug(
                                f"Inserted Word table for '{clean_text.strip()}' "
                                f"({len(rows)} row(s) × {n_cols} col(s))"
                            )
                        except Exception as tbl_err:
                            logging.warning(
                                f"Could not insert table for '{clean_text.strip()}': {tbl_err}; "
                                "writing placeholder as plain text"
                            )
                            doc.add_paragraph(clean_text)
                    _insert_frac_images_up_to(para_fraction)
                    continue

                # --- Regular paragraph ---
                try:
                    paragraph = doc.add_paragraph(clean_text)
                    paragraph_format = paragraph.paragraph_format
                    paragraph_format.space_after = Pt(12)
                    paragraph_format.line_spacing = 1.5

                    if paragraph.runs:
                        for run in paragraph.runs:
                            run.font.name = font_name
                            run.font.size = Pt(fs)
                    else:
                        run = paragraph.add_run(clean_text)
                        run.font.name = font_name
                        run.font.size = Pt(fs)

                    logging.debug(f"Successfully added paragraph {i} with font {font_name}")
                except Exception as paragraph_error:
                    logging.warning(f"Error processing paragraph {i} for Word document: {paragraph_error}")
                    try:
                        doc.add_paragraph(clean_text)
                        logging.debug(f"Added paragraph {i} with basic formatting")
                    except Exception as fallback_error:
                        logging.warning(f"Failed to add paragraph {i} to Word document: {fallback_error}")
                        _insert_frac_images_up_to(para_fraction)
                        continue

                _insert_frac_images_up_to(para_fraction)

            # Append any remaining images that fall past the last paragraph.
            _flush_pending_pdf_images()
            _insert_frac_images_up_to(1.0)

            # Save the document
            if len(doc.paragraphs) > 0:
                doc.save(output_path)
                FileOutputHandler._emit_message(
                    f"{label} saved to Word document: {Path(output_path).name}",
                    level=logging.INFO,
                    log_message=f'{label} saved to Word document: {output_path}',
                    leading_newline=True,
                )
                if font_name != 'Times New Roman':
                    FileOutputHandler._emit_message(f"Used font: {font_name}", level=logging.DEBUG)
            else:
                FileOutputHandler._emit_message(
                    "Error: No content could be processed for Word document generation",
                    level=logging.ERROR,
                    log_message="No content could be processed for Word document generation",
                )
                FileOutputHandler._fallback_to_text(content, output_path, label)

        except ImportError:
            FileOutputHandler._emit_message(
                "Warning: python-docx not installed. To enable Word document export, install it with:",
                level=logging.WARNING,
                log_message='python-docx not installed. Falling back to text file.',
            )
            print("pip install python-docx")
            FileOutputHandler._emit_message("Saving as text file instead.", level=logging.WARNING)
            FileOutputHandler._fallback_to_text(content, output_path, label)
        except Exception as e:
            FileOutputHandler._emit_message(
                f"Error generating Word document: {e}",
                level=logging.ERROR,
                log_message=f'Error saving to Word document: {e}',
            )
            FileOutputHandler._emit_message(
                "Falling back to text file for reliable CJK character support...",
                level=logging.WARNING,
            )
            FileOutputHandler._fallback_to_text(content, output_path, label)
    
    @staticmethod
    def save_translation_output(content: str, input_file: Optional[str], output_file: Optional[str],
                              auto_save: bool, source_lang: str, target_lang: str,
                              custom_font: Optional[str] = None,
                              media: Optional[List] = None,
                              table_registry: Optional[dict] = None,
                              font_size: Optional[int] = None,
                              *,
                              label: str) -> None:
        """Save translation output to file based on user preferences."""
        if not content.strip():
            FileOutputHandler._emit_message("No content to save.", level=logging.INFO)
            return
        
        output_path = FileOutputHandler._resolve_output_path(
            input_file,
            output_file,
            auto_save,
            source_lang,
            target_lang,
            '.txt',
        )
        if not output_path:
            return
        
        FileOutputHandler._ensure_parent_directory(output_path)

        extension = Path(output_path).suffix.lower()
        if extension == '.pdf':
            FileOutputHandler.save_to_pdf(
                content, output_path, custom_font, target_lang,
                table_registry=table_registry,
                font_size=font_size,
                label=label,
            )
            return
        if extension == '.docx':
            FileOutputHandler.save_to_docx(
                content, output_path, custom_font, target_lang,
                media=media, table_registry=table_registry,
                font_size=font_size,
                label=label,
            )
            return

        if extension != '.txt':
            output_path = f"{output_path}.txt"
        FileOutputHandler.save_to_text_file(
            FileOutputHandler._render_markdown_tables_as_ascii(content),
            output_path,
            label=label,
        )

    @staticmethod
    def save_page_progressively(content: str, input_file: Optional[str], output_file: Optional[str],
                               auto_save: bool, source_lang: str, target_lang: str, label: str, is_first_page: bool = False,
                               custom_font: Optional[str] = None) -> Optional[str]:
        """Save a single page progressively to output file. Returns the output path."""
        _ = custom_font
        if not content.strip():
            FileOutputHandler._emit_message("No content to save.", level=logging.INFO)
            return None
        
        output_path = FileOutputHandler._resolve_output_path(
            input_file,
            output_file,
            auto_save,
            source_lang,
            target_lang,
            '.txt',
        )
        if not output_path:
            return None
        
        FileOutputHandler._ensure_parent_directory(output_path)
        
        # For progressive saving, we currently only support text files
        # PDF and Word document merging is complex and requires additional dependencies
        extension = Path(output_path).suffix.lower()
        if extension == '.pdf':
            FileOutputHandler._emit_message(
                "Note: Progressive saving for PDF format not yet supported. Using text format.",
                level=logging.INFO,
            )
            output_path = str(Path(output_path).with_suffix('.txt'))
        elif extension == '.docx':
            FileOutputHandler._emit_message(
                "Note: Progressive saving for Word document format not yet supported. Using text format.",
                level=logging.INFO,
            )
            output_path = str(Path(output_path).with_suffix('.txt'))
        
        # Default to text file
        if Path(output_path).suffix.lower() != '.txt':
            output_path = f"{output_path}.txt"
        
        # Save first page or append subsequent pages
        if is_first_page:
            FileOutputHandler.save_to_text_file(content, output_path, label)
        else:
            FileOutputHandler.append_to_text_file(content, output_path, label)
        
        return output_path
